function create_profileviewer_gui(hObject,eventdata,handles)
global custom default;  %default settings and customed settings
%global nsite sitename location data; %edi sites:number,sitename,location,
hpvmain=figure;
enable_color=[1 1 1];
set(hpvmain,'units','normalized','position',[0.1 0.1 0.8 0.8],'numbertitle','off',...
    'name','Profile Section Viewer');
bcolor=get(hpvmain,'color');
haa=axes('units','normalized','position',[0.05 0.1 0.6 0.85],'tag','axisa');
hasite=axes('units','normalized','position',[0.72 0.6 0.25 0.35],'tag','axissite');
%plot grid before colorbar emerges
subplot_mesh(hObject,eventdata,hasite)
%================colorbar=================%
colormap(flipud(jet(64)));
hcb=colorbar('units','normalized','position',[0.74 0.05 0.05 0.2]);
caxis([log10(default.rhomin),log10(default.rhomax)]);
hrmax=uicontrol(hpvmain,'style','edit','units','normalized','position',...
    [0.81 0.22 0.04 0.03],'string',num2str(default.rhomax),'backgroundcolor',...
    enable_color,'enable','off');
hrmin=uicontrol(hpvmain,'style','edit','units','normalized','position',...
    [0.81 0.05 0.04 0.03],'string',num2str(default.rhomin),'backgroundcolor',...
    enable_color,'enable','off');

%button group 'Settings'
hbgset=uibuttongroup(hpvmain,'units','normalized','position',...
    [0.73 0.28 0.22 0.25],'title','settings','backgroundcolor',bcolor,...
    'tag','','fontweight','bold');
hcbset_boundary= uicontrol(hbgset,'style','checkbox','units','normalized','position',...
    [0.05 0.85 0.4 0.15],'string','set boundary','tag','set boundary', ...
    'value',1,'backgroundcolor',bcolor,'tooltipstring','set boundary');
hcbset_3d= uicontrol(hbgset,'style','checkbox','units','normalized',...
    'position',[0.5 0.85 0.4 0.15],'value',1,'string','view in 3D',...
    'tag','view in 3D', ...
    'backgroundcolor',bcolor,...
    'value', 0,...
    'tooltipstring','view profile in 3D');
heXboundary= uicontrol(hbgset,'style','edit','units','normalized','position',...
    [0.1 0.70 0.25 0.15],'string',num2str(custom.x2),'tag','X','backgroundcolor',...
    enable_color);
heYboundary= uicontrol(hbgset,'style','edit','units','normalized','position',...
    [0.4 0.70 0.25 0.15],'string',num2str(custom.y2),'tag','Y','backgroundcolor',...
    enable_color);
heZboundary= uicontrol(hbgset,'style','edit','units','normalized','position',...
    [0.7 0.70 0.25 0.15],'string',num2str(custom.z4),'tag','Z','backgroundcolor',...
    enable_color);
htDAR_text = uicontrol(hbgset,'style','text','units','normalized','position',...
    [0.05 0.4 0.6 0.15],'string','Data Aspect Ratio: (h/v)','backgroundcolor',bcolor);
hDAR = uicontrol(hbgset,'style','edit','units','normalized','position',...
    [0.7 0.44 0.2 0.15],'string','1','tag','Z','backgroundcolor',...
    enable_color);
htmap_text = uicontrol(hbgset,'style','text','units','normalized','position',...
    [0.05 0.22 0.3 0.15],'string','color map','backgroundcolor',bcolor);
hpopmap = uicontrol(hbgset,'Style', 'popup','units','normalized',...
       'String', 'reversed jet|HSV|gray|jet|reversed HSV|jet w/topo|rainbow',...
       'Position', [0.45 0.23 0.3 0.15]);
htshade_text = uicontrol(hbgset,'style','text','units','normalized','position',...
    [0.05 0.05 0.3 0.15],'string','shading','backgroundcolor',bcolor);
hpopshade = uicontrol(hbgset,'Style', 'popup','units','normalized',...
       'String', 'interp|flat|faceted',...
       'Position',  [0.45 0.07 0.3 0.15]);
% other buttons
hpbcopypic=uicontrol(hpvmain,'style','pushbutton','units','normalized','position',...
    [0.87 0.10 0.07 0.04],'string','Copy Pic','tag','copy selected axis');
hpbquit=uicontrol(hpvmain,'style','pushbutton','units','normalized','position',...
    [0.87 0.05 0.07 0.04],'string','DONE','tag','quit');
hpbplot_profile=uicontrol(hpvmain,'style','pushbutton','units','normalized','position',...
    [0.87 0.15 0.07 0.04],'string','NEW','tag','make profile', ...
    'backgroundcolor',bcolor,'tooltipstring','make profile');
hpbsavexyz=uicontrol(hpvmain,'style','pushbutton','units','normalized','position',...
    [0.87 0.20 0.07 0.04],'string','Save XYZ','tag','save selected axis in XYZ');

% create a menu for further use
m_toggle = uimenu( 'Parent', hpvmain, 'Label', 'toggle' );
m_toggle_pseudo = uimenu('Parent',m_toggle,'Label','toggle pseudo mode');

% put all handles into a structure
handles.axis=[haa,hasite];
handles.buttons=[hpbcopypic,hpbplot_profile,hpbquit,hpbsavexyz];
handles.setbox=[hcbset_boundary,hpopmap,hpopshade,htmap_text,htshade_text,...
    heXboundary,heYboundary,heZboundary,htDAR_text,hDAR];
handles.set3D=hcbset_3d;
handles.parent=handles;
handles.colorbar=hcb;
handles.rholim=[hrmin,hrmax];
handles.figure=hpvmain;

% set ui callbacks
set(hpbquit,'callback',{@quit_this,hpvmain})
set(hrmax,'callback',{@set_colorbar,handles})
set(hrmin,'callback',{@set_colorbar,handles})
set(hpbplot_profile,'callback',{@plot_profiles,handles})
set(hpopshade,'callback',{@set_shading,handles})
set(hpbcopypic,'callback',{@copy_pic,handles})
set(hpopmap,'callback',{@set_profile_map,handles});
set(hcbset_boundary,'callback',{@set_boundary,handles})
set(heXboundary,'callback',{@set_boundary,handles})
set(heYboundary,'callback',{@set_boundary,handles})
set(heZboundary,'callback',{@set_boundary,handles})
set(hpbsavexyz,'callback',{@save_xyz,handles});
set(m_toggle_pseudo,'callback',{@toggle_pseudo,handles});
% a little initial works
set(handles.setbox,'enable','on')
set(handles.buttons,'enable','on')
set(handles.rholim,'enable','on')
figtoolbar(handles);
return

