function create_resultviewer_gui(hObject,eventdata,handles)
global custom default;  %default settings and customed settings
%global nsite sitename location data; %edi sites:number,sitename,location,
hrvmain=figure;
enable_color=[1 1 1];
screen_pos=check_res();
set(hrvmain,'units','pixel',...
    'position',screen_pos,...
    'numbertitle','off',...
    'name','plot results & models');
bcolor=get(hrvmain,'color');
haa=axes('units','normalized',...
    'position',[0.05 0.55 0.4 0.4],...
    'tag','axisa');
hab=axes('units','normalized',...
    'position',[0.55 0.55 0.4 0.4],...
    'tag','axisb');
hac=axes('units','normalized',...
    'position',[0.05 0.05 0.4 0.4],...
    'tag','axissite');
custom=default;
%================colorbar=================%
colormap(flipud(jet(64))); % use a upside down jet64 colormap for plot.
hcb=colorbar('units','normalized',...
    'position',[0.78 0.12 0.05 0.2]);
caxis([log10(default.rhomin),log10(default.rhomax)]);
hrmax=uicontrol(hrvmain,'style','edit',...
    'units','normalized',...
    'position',[0.84 0.29 0.04 0.03],...
    'string',num2str(default.rhomax),...
    'backgroundcolor',enable_color,...
    'enable','off');
hrmin=uicontrol(hrvmain,'style','edit','units','normalized','position',...
    [0.84 0.12 0.04 0.03],'string',num2str(default.rhomin),'backgroundcolor',...
    enable_color,'enable','off');
% create a menu for futural use
m_batch = uimenu( 'Parent', hrvmain, 'Label', 'Batch' );
m_batch_pic = uimenu('Parent',m_batch,'Label','Batch output pics');
m_batch_xyz = uimenu('Parent',m_batch,'Label','Batch output xyzs');
m_batch_xyr = uimenu('Parent',m_batch,'Label','Batch output rms distribution');
m_batch_xyzv = uimenu('Parent',m_batch,'Label','Batch output xyzvs');
m_batch_response = uimenu('Parent',m_batch,'Label','Batch output responses');
m_batch_plot_response = uimenu('Parent',m_batch,'Label','Batch plot responses');
m_batch_plot_resp4 = uimenu('Parent',m_batch,'Label','Batch plot all responses');
m_batch_aver_model = uimenu('Parent',m_batch,'Label','Batch average models');
m_output_1d = uimenu('Parent',m_batch,'Label','export 1D model');
m_export_cond = uimenu('Parent',m_batch,'Label','export conductance');
m_export_visco = uimenu('Parent',m_batch,'Label','export viscosity');
m_export_tz = uimenu( 'Parent', m_batch, 'Label', 'export TZ vector'); 
m_export_rhophs = uimenu( 'Parent', m_batch, 'Label', 'export RHO/PHS files'); 
m_settings = uimenu( 'Parent', hrvmain, 'Label', 'Settings' );
m_set_ratio = uimenu( 'Parent', m_settings, 'Label', 'set h/v ratio'); 
m_save_siteloc = uimenu( 'Parent', m_settings, 'Label', 'save a site location list');


%button group 'View'
hbgview=uibuttongroup(hrvmain,'units','normalized','position',...
    [0.55 0.35 0.2 0.15],'title','set aspect','backgroundcolor',bcolor,...
    'tag','','fontweight','bold');
h3d_multi_slice=uicontrol(hbgview,'style','radiobutton','units','normalized','position',...
    [0.05 0.7 0.7 0.25],'string','view 3d in ','tag','view 3d all', ...
    'backgroundcolor',bcolor,'tooltipstring','view 3d mode');
h3d_single_slice=uicontrol(hbgview,'style','radiobutton','units','normalized','position',...
    [0.05 0.2 0.4 0.25],'string','view 3d','tag','view 3d', ...
    'backgroundcolor',bcolor,'tooltipstring','view 3d mode');
h2d_slice=uicontrol(hbgview,'style','radiobutton','units','normalized','position',...
    [0.55 0.2 0.4 0.25],'string','view 2d','tag','view 2d', ...
    'backgroundcolor',bcolor,'tooltipstring','view 2d mode');
h3d_nslice=uicontrol(hbgview,'style','Edit','units','normalized','position',...
    [0.55 0.7 0.2 0.25],'string','5','tag','nslice', ...
    'tooltipstring','set number of slice to display');
h3d_text=uicontrol(hbgview,'style','text','units','normalized','position',...
    [0.75 0.65 0.2 0.25],'string','slices','tag','nslice', ...
    'backgroundcolor',bcolor);

%button group 'SELECTION'
hbgselection=uibuttongroup(hrvmain,'units','normalized','position',...
    [0.55 0.05 0.2 0.3],'title','selection','backgroundcolor',bcolor,...
    'tag','','fontweight','bold');
hsx=uicontrol(hbgselection,'style','radiobutton','units','normalized','position',...
    [0.05 0.8 0.4 0.15],'string','X(LAT)','tag','slice in x direction', ...
    'backgroundcolor',bcolor,'tooltipstring','slice in x direction');
hsy=uicontrol(hbgselection,'style','radiobutton','units','normalized','position',...
    [0.05 0.6 0.4 0.15],'string','Y(LONG)','tag','slice in y direction', ...
    'backgroundcolor',bcolor,'tooltipstring','slice in y direction');
hsz=uicontrol(hbgselection,'style','radiobutton','units','normalized','position',...
    [0.05 0.4 0.4 0.15],'string','Z(DEPTH)','tag','slice in y direction', ...
    'backgroundcolor',bcolor,'tooltipstring','slice in y direction');
hsxlocation=uicontrol(hbgselection,'style','edit','units','normalized','position',...
    [0.55 0.8 0.4 0.15],'string','0','backgroundcolor',enable_color);
hsylocation=uicontrol(hbgselection,'style','edit','units','normalized','position',...
    [0.55 0.6 0.4 0.15],'string','0','backgroundcolor',enable_color);
hszlocation=uicontrol(hbgselection,'style','edit','units','normalized','position',...
    [0.55 0.4 0.4 0.15],'string','0','backgroundcolor',enable_color);
hszoomin=uicontrol(hbgselection,'style','checkbox','units','normalized','position',...
    [0.05 0.2 0.7 0.15],'string','show profile area only','tag','zoomin',...
    'backgroundcolor',bcolor);
hpbprevious=uicontrol(hbgselection,'style','pushbutton','units','normalized','position',...
    [0.05 0.05 0.4 0.15],'string','previous','tag','previous site');
hpbnext=uicontrol(hbgselection,'style','pushbutton','units','normalized','position',...
    [0.55 0.05 0.4 0.15],'string','next','tag','next site');

% button group 'Settings'
hbgset=uibuttongroup(hrvmain,'units','normalized','position',...
    [0.77 0.35 0.2 0.15],'title','settings','backgroundcolor',bcolor,...
    'tag','','fontweight','bold');
hcbset_boundary= uicontrol(hbgset,'style','checkbox','units','normalized','position',...
    [0.05 0.77 0.4 0.20],'string','set boundary','tag','set boundary', ...
    'backgroundcolor',bcolor,'tooltipstring','set boundary');
hcbplot_site = uicontrol (hbgset,'style','checkbox','units','normalized','position',...
    [0.55 0.77 0.4 0.2],'string','plot sites','tag','plot site', ...
    'backgroundcolor',bcolor,'tooltipstring','plot site');
heXboundary= uicontrol(hbgset,'style','edit','units','normalized','position',...
    [0.1 0.55 0.25 0.2],'string',num2str(custom.x2),'tag','X','backgroundcolor',...
    enable_color);
heYboundary= uicontrol(hbgset,'style','edit','units','normalized','position',...
    [0.4 0.55 0.25 0.2],'string',num2str(custom.y2),'tag','Y','backgroundcolor',...
    enable_color);
heZboundary= uicontrol(hbgset,'style','edit','units','normalized','position',...
    [0.7 0.55 0.25 0.2],'string',num2str(custom.z4),'tag','Z','backgroundcolor',...
    enable_color);
htmap_text = uicontrol(hbgset,'style','text','units','normalized','position',...
    [0.05 0.32 0.35 0.15],'string','color map','backgroundcolor',bcolor);
hpopmap = uicontrol(hbgset,'Style', 'popup','units','normalized',...
       'String', 'reversed jet|HSV|gray|jet|reversed HSV|jet w/ topo|Rainbow|R jet16',...
       'Position', [0.55 0.3 0.35 0.2]);
htshade_text = uicontrol(hbgset,'style','text','units','normalized','position',...
    [0.05 0.12 0.35 0.15],'string','shading','backgroundcolor',bcolor);
hpopshade = uicontrol(hbgset,'Style', 'popup','units','normalized',...
       'String', 'interp|flat|faceted',...
       'Position',  [0.55 0.1 0.35 0.2]);

%button group 'Set Transparency'
%sealed for good
%{
hbgTrans=uibuttongroup(hrvmain,'units','normalized','position',...
    [0.77 0.35 0.2 0.15],'title','Set Transparency','backgroundcolor',bcolor,...
    'tag','','fontweight','bold');
hcboxenable_trans=uicontrol(hbgTrans,'style','checkbox','units','normalized','position',...
    [0.05 0.75 0.8 0.25],'string','enable transparent view','tag','enable trans', ...
    'backgroundcolor',bcolor,'tooltipstring','enable trans');
htranslider=uicontrol(hbgTrans,'style','slider','units','normalized','position',...
    [0.1 0.4 0.8 0.2],'value',1,'backgroundcolor',enable_color);
htranstext=uicontrol(hbgTrans,'style','text','units','normalized','position',...
    [0.4 0.15 0.2 0.2],'string','1','backgroundcolor',bcolor);
%}


% other buttons
hpbresp=uicontrol(hrvmain,'style','pushbutton','units','normalized','position',...
    [0.9 0.14 0.06 0.04],'string','view resp','tag','view resp');
hpbrms=uicontrol(hrvmain,'style','pushbutton','units','normalized','position',...
    [0.9 0.19 0.06 0.04],'string','view rms','tag','view rms');
hpbcopypic=uicontrol(hrvmain,'style','pushbutton','units','normalized','position',...
    [0.9 0.24 0.06 0.04],'string','Copy Pic','tag','copy selected axis');
hpbload=uicontrol(hrvmain,'style','pushbutton','units','normalized','position',...
    [0.79 0.03 0.08 0.05],'string','LOAD model','tag','load model');
hpbquit=uicontrol(hrvmain,'style','pushbutton','units','normalized','position',...
    [0.89 0.03 0.08 0.05],'string','DONE','tag','quit');
hpbisoview=uicontrol(hrvmain,'style','pushbutton','units','normalized','position',...
    [0.9 0.29 0.06 0.04],'string','view isosfc','tag','isosurface');
hpbprofile=uicontrol(hrvmain,'style','pushbutton','units','normalized','position',...
    [0.9 0.09 0.06 0.04],'string','profile','tag','profile');
htext=uicontrol(hrvmain,'style','text','units','normalized','position',...
    [0.45 0.95 0.1 0.03],'string','RMS','backgroundcolor',bcolor);


% put all handles into a structure
handles.axis=[haa,hab,hac];
handles.buttons=[hpbresp,hpbrms,hpbcopypic,hpbisoview,hpbprofile];
handles.selectionbox=[hsx,hsy,hsz,hsxlocation,hsylocation,hszlocation,...
    hszoomin,hpbprevious,hpbnext];
handles.viewbox=[h3d_multi_slice,h3d_single_slice,h2d_slice,h3d_nslice,h3d_text];
handles.setbox=[hcbset_boundary,hpopmap,hpopshade,htmap_text,htshade_text,...
    heXboundary,heYboundary,heZboundary,hcbplot_site];
%handles.transbox=[htranslider,htranstext,hcboxenable_trans];
handles.parent=handles;
handles.text=htext;
handles.colorbar=hcb;
handles.rholim=[hrmin,hrmax];
handles.figure=hrvmain;
handles.menu=[m_batch,m_batch_pic,m_batch_xyz,m_batch_xyr,...
    m_settings,m_batch_xyzv,m_batch_response,...
    m_export_cond,m_export_tz,m_output_1d,m_export_visco, m_export_rhophs];
handles.settings=[m_settings,m_set_ratio,m_save_siteloc];

% set ui callbacks
set(m_batch_pic,'callback',{@batch_pic_output,handles})
set(m_batch_xyz,'callback',{@batch_xyz_output,handles})
set(m_batch_xyr,'callback',{@batch_xyr_output,handles})
set(m_batch_xyzv,'callback',{@batch_xyzv_output,handles})
set(m_batch_response,'callback',{@batch_response_output,handles})
set(m_batch_plot_response,'callback',{@batch_plot_response,handles})
set(m_batch_aver_model,'callback',{@batch_aver_model,handles})
set(m_batch_plot_resp4,'callback',{@batch_plot_resp4,handles})
set(m_export_cond,'callback',{@export_cond_dlg,handles});
set(m_export_visco,'callback',{@export_visco_dlg,handles});
set(m_export_tz,'callback',{@batch_tz_output,handles});
set(m_export_rhophs,'callback',{@batch_rhophs_output,handles});
set(m_output_1d,'callback',{@export_1Dmodel,handles})
set(m_set_ratio,'callback',{@set_ratio,handles});
set(m_save_siteloc,'callback',{@save_siteloc,handles});
set(hpbquit,'callback',{@quit_this,hrvmain})
set(hpbload,'callback',{@load_results,handles})
set(h3d_multi_slice,'callback',{@subview,handles})
set(h3d_single_slice,'callback',{@subview,handles})
set(h2d_slice,'callback',{@subview,handles})
set(h3d_nslice,'callback',{@subview,handles})
set(hpbprevious,'callback',{@next_slice,handles,'previous'})
set(hpbnext,'callback',{@next_slice,handles,'next'})
set(hrmax,'callback',{@set_colorbar,handles})
set(hrmin,'callback',{@set_colorbar,handles})
set(hsxlocation,'callback',{@set_slice_location,handles,'x'})
set(hsylocation,'callback',{@set_slice_location,handles,'y'})
set(hszlocation,'callback',{@set_slice_location,handles,'z'})
set(hszoomin,'callback',{@subview,handles})
%set(htranslider,'callback',{@set_trans,handles})
%set(hcboxenable_trans,'callback',{@enable_trans,handles})
set(hpbresp,'callback',{@create_resp_gui,handles})
set(hpbrms,'callback',@create_rms_gui)
set(hpbcopypic,'callback',{@copy_pic,handles})
% settings callbacks 
set(hpopshade,'callback',{@set_shading,handles})
set(hpopmap,'callback',{@set_colormap,handles});
set(hcbset_boundary,'callback',{@set_boundary,handles})
set(hcbplot_site,'callback',{@subview,handles})
set(heXboundary,'callback',{@set_boundary,handles})
set(heYboundary,'callback',{@set_boundary,handles})
set(heZboundary,'callback',{@set_boundary,handles})
% subfunction callbacks
set(hpbisoview,'callback',@create_isosfc_gui)
set(hpbprofile,'callback',@create_profileviewer_gui)
%set(hbodyminrho,'callback',{@bodyview,handles});
%set(hbodymaxrho,'callback',{@bodyview,handles});
% start ploting
%subplot_site(hObject,eventdata,handles);
%plot_sounding(hObject,eventdata,handles,'xy');
% a litte init works
%set(htranslider,'Max',1);
%set(htranslider,'Min',0);
set(handles.selectionbox,'enable','off')
set(handles.viewbox,'enable','off')
set(handles.setbox,'enable','off')
%set(handles.transbox,'enable','off')
set(handles.buttons,'enable','off')
set(handles.buttons(2),'enable','on')
figtoolbar(handles);
return

