function create_freqeditor_gui(hObject,eventdata,handle)
global custom
hdmain=figure;
bcolor=get(hdmain,'color');
enable_color=[1 1 1];
set(hdmain,'units','normalized',...
    'position',[0.4 0.4 0.3 0.3],...
    'numbertitle','off',...
    'name','data freq editor');

% button group data select
hfds=uipanel(hdmain,'units',...
    'normalized','position',...
    [0.05 0.05 0.65 0.9],'title',...
    'data select','backgroundcolor',...
    bcolor,'fontweight','bold');
hsmooth=uicontrol(hfds,'style','checkbox',...
    'units','normalized',...
    'position',[0.05, 0.87, 0.50, 0.12],...
    'string','use smoothed data',...
    'value',~custom.origin,...
    'backgroundcolor',bcolor);
ht11=uicontrol(hfds,'style','text','units','normalized','position',...
    [0.05 0.72 0.22 0.10],'string','Segment 1:','backgroundcolor',bcolor);
hfdsfmax1=uicontrol(hfds,'style','edit','units','normalized','position',...
    [0.32 0.75 0.25 0.10],'string','0.01',...
    'backgroundcolor',enable_color,'enable','off');
ht12=uicontrol(hfds,'style','text','units','normalized','position',...
    [0.57 0.72 0.07 0.10],'string','~','backgroundcolor',bcolor);
hfdsfmin1=uicontrol(hfds,'style','edit','units','normalized','position',...
    [0.66 0.75 0.25 0.10],'string','1',...
    'backgroundcolor',enable_color,'enable','off');
ht13=uicontrol(hfds,'style','text','units','normalized','position',...
    [0.94 0.72 0.05 0.10],'string','S','backgroundcolor',bcolor);
ht14=uicontrol(hfds,'style','text','units','normalized','position',...
    [0.05 0.58 0.30 0.10],'string','periods/decade:','backgroundcolor',bcolor);
hfdsfpb1=uicontrol(hfds,'style','edit','units','normalized','position',...
    [0.40 0.61 0.25 0.10],'string',num2str(custom.ppd(1)),...
    'backgroundcolor',enable_color,'enable','off');
ht15=uicontrol(hfds,'style','text','units','normalized','position',...
    [0.05 0.32 0.22 0.10],'string','Segment 2:','backgroundcolor',bcolor);
hfdsfmax2=uicontrol(hfds,'style','edit','units','normalized','position',...
    [0.32 0.35 0.25 0.10],'string','1',...
    'backgroundcolor',enable_color,'enable','off');
ht16=uicontrol(hfds,'style','text','units','normalized','position',...
    [0.57 0.32 0.07 0.10],'string','~','backgroundcolor',bcolor);
hfdsfmin2=uicontrol(hfds,'style','edit','units','normalized','position',...
    [0.66 0.35 0.25 0.10],'string','1000',...
    'backgroundcolor',enable_color,'enable','off');
ht17=uicontrol(hfds,'style','text','units','normalized','position',...
    [0.94 0.32 0.05 0.10],'string','S','backgroundcolor',bcolor);
ht18=uicontrol(hfds,'style','text','units','normalized','position',...
    [0.05 0.18 0.30 0.10],'string','periods/decade:','backgroundcolor',bcolor);
hfdsfpb2=uicontrol(hfds,'style','edit','units','normalized','position',...
    [0.40 0.21 0.25 0.10],'string',num2str(custom.ppd(1)),...
    'backgroundcolor',enable_color,'enable','off');


hlistperiod=uicontrol(hfds,'style','pushbutton','units','normalized','position',...
    [0.75 0.07 0.20 0.10],'string','List Freq');

% other buttons
hpbload=uicontrol(hdmain,'style','pushbutton','units','normalized','position',...
    [0.75 0.25 0.2 0.15],'string','load file','tag','load');
hpbquit=uicontrol(hdmain,'style','pushbutton','units','normalized','position',...
    [0.75 0.05 0.2 0.15],'string','DONE','tag','exit');
hpbmanual=uicontrol(hdmain,'style','pushbutton','units','normalized','position',...
    [0.75 0.45 0.2 0.15],'string','manual','tag','exit');
handle.smooth=[hsmooth,hfdsfmax1, hfdsfmin1, hfdsfpb1, hfdsfmax2, hfdsfmin2, ...
    hfdsfpb2];
handle.tmp=[ht11, ht12, ht13, ht14, ht15, ht16, ht17, ht18];
% set ui callbacks
set(hlistperiod,'callback',@list_freq);
set(hsmooth,'callback',{@toggle_smooth,handle});
set(handle.smooth,'enable','on');
set(handle.smooth(2),'callback',{@set_flist2,handle});
set(handle.smooth(3),'callback',{@set_flist2,handle});
set(handle.smooth(4),'callback',{@set_flist2,handle});
set(handle.smooth(5),'callback',{@set_flist2,handle});
set(handle.smooth(6),'callback',{@set_flist2,handle});
set(handle.smooth(7),'callback',{@set_flist2,handle});
set(hpbquit,'callback',{@quit_this,hdmain});
set(hpbload,'callback',@load_freqtable);
set(hpbmanual,'callback',@edit_freqtable);
return

