function create_isosfc_gui(hObject,eventdata)
global model custom
% v 0.2
% previously designed for standalone plot work
% intergrated with EM3D
% for isosurface and slice plot
x=model.x;
y=model.y;
z=model.z;
V = log10(model.rho);
hisomain=figure;
rholimit=[min(V(:)),max(V(:))];
set(hisomain,'units','normalized','position',[0.2 0.2 0.6 0.6],'numbertitle','off',...
    'name','isosurface viewer');
bcolor=get(hisomain,'color');
enable_color=[1 1 1];
haa = axes('units','normal','pos',[.1  .2 .6 .7],'tag','isosurface','clim',rholimit);
%================colorbar=================%
colormap(flipud(jet(64)));
hcolorbar=colorbar('units','normalized','position',[0.73 0.07 0.06 0.25]);
caxis([log10(custom.rhomin),log10(custom.rhomax)]);
hrmax=uicontrol(hisomain,'style','edit','units','normalized','position',...
    [0.80 0.27 0.07 0.05],'string',num2str(custom.rhomax),'backgroundcolor',...
    enable_color);
hrmin=uicontrol(hisomain,'style','edit','units','normalized','position',...
    [0.80 0.07 0.07 0.05],'string',num2str(custom.rhomin),'backgroundcolor',...
    enable_color);
%set color limits
hpbload=uicontrol(hisomain,'style','pushbutton','units','normalized','position',...
    [0.89 0.21 0.08 0.05],'string','load model','tag','load model');
hpbquit=uicontrol(hisomain,'style','pushbutton','units','normalized','position',...
    [0.89 0.07 0.08 0.05],'string','DONE','tag','quit');
hpbcopypic=uicontrol(hisomain,'style','pushbutton','units','normalized','position',...
    [0.89 0.14 0.08 0.05],'string','Copy Pic','tag','copy current axis');
%button group "isosurface"
hbgisosfc=uibuttongroup(hisomain,'units','normalized','position',...
    [0.73 0.35 0.25 0.2],'title','isosurface','backgroundcolor',bcolor,...
    'tag','','fontweight','bold');
hiso_value=uicontrol(hbgisosfc,'style','edit','units','normalized','position',...
    [0.45 0.6 0.5 0.25],'string','10','tag','value', ...
    'backgroundcolor',bcolor);
hiso_text=uicontrol(hbgisosfc,'style','text','units','normalized','position',...
    [0.05 0.57 0.3 0.25],'string','rho value','tag','rho value', ...
    'backgroundcolor',bcolor);
hiso_plot=uicontrol(hbgisosfc,'style','pushbutton','units','normalized','position',...
    [0.65 0.15 0.3 0.26],'string','plot','tag','plot', ...
    'backgroundcolor',bcolor);
hcb_camlight=uicontrol(hbgisosfc,'style','checkbox','units','normalized','position',...
    [0.05 0.15 0.3 0.26],'string','camlight','tag','camlight', ...
    'backgroundcolor',bcolor);
%button group "slices"
hbgslice=uibuttongroup(hisomain,'units','normalized','position',...
    [0.73 0.55 0.25 0.45],'title','slices','backgroundcolor',bcolor,...
    'tag','slices','fontweight','bold');
htextx=uicontrol(hbgslice,'style','text','units','normalized','position',...
    [0.05 0.83 0.3 0.1],'string','x location','tag','x', ...
    'backgroundcolor',bcolor);
hslicex=uicontrol(hbgslice,'style','edit','units','normalized','position',...
    [0.45 0.85 0.5 0.1],'string','0','tag','x location', ...
    'backgroundcolor',bcolor);
htexty=uicontrol(hbgslice,'style','text','units','normalized','position',...
    [0.05 0.68 0.3 0.1],'string','y location','tag','x', ...
    'backgroundcolor',bcolor);
hslicey=uicontrol(hbgslice,'style','edit','units','normalized','position',...
    [0.45 0.70 0.5 0.1],'string','0','tag','y location', ...
    'backgroundcolor',bcolor);
htextz=uicontrol(hbgslice,'style','text','units','normalized','position',...
    [0.05 0.53 0.3 0.1],'string','z location','tag','x', ...
    'backgroundcolor',bcolor);
hslicez=uicontrol(hbgslice,'style','edit','units','normalized','position',...
    [0.45 0.55 0.5 0.1],'string','-20','tag','z location', ...
    'backgroundcolor',bcolor);
hpbcut=uicontrol(hbgslice,'style','pushbutton','units','normalized','position',...
    [0.65 0.05 0.3 0.1],'string','CUT!','tag','z location', ...
    'backgroundcolor',bcolor);
hszoomin=uicontrol(hbgslice,'style','checkbox','units','normalized','position',...
    [0.15 0.40 0.7 0.1],'string','show profile area only','tag','zoomin',...
    'backgroundcolor',bcolor);
htranstext=uicontrol(hbgslice,'style','text','units','normalized','position',...
    [0.35 0.13 0.3 0.1],'string','1','tag','alpha', ...
    'backgroundcolor',bcolor);
htranslider=uicontrol(hbgslice,'style','slider','units','normalized','position',...
    [0.15 0.27 0.7 0.08],'value',1,'backgroundcolor',enable_color);

%color limits

%set handles
h.colorbar=hcolorbar;
h.axis=haa;
h.rholim=[hrmin,hrmax];
h.isobox=[hiso_value,hiso_text,hiso_plot,hbgisosfc,hcb_camlight];
h.slicebox=[hslicex,hslicey,hslicez,htextx,htexty,htextz,hpbcut,hszoomin];
h.transbox=[htranslider,htranstext];
h.figure=hisomain;
set(htranslider,'callback',{@set_isotrans,h})
set(hpbquit,'callback',{@quit_this,hisomain});
set(hpbload,'callback',{@load_model_only,h});
set(hpbcopypic,'callback',{@copy_pic,h})% call the copypic function of main gui...
set(hcolorbar,'buttondownfcn',{@iso_callback,h,'add'});
set(hiso_plot,'callback',{@plot_iso,h});
set(hpbcut,'callback',{@cut,h});
set(hszoomin,'callback',{@cut,h});
set(hcb_camlight,'callback',{@plot_iso,h});
set(hrmin,'callback',{@set_colorbar,h});
set(hrmax,'callback',{@plot_iso,h});
daspect([1 1 1])
view(3); 
box on
grid on
axis auto;
axis([min(x) max(x) min(y) max(y) min(z) max(z)]);
set(hisomain,'toolbar','figure')
% hold on;
% oidd=slice(h.axis,X,Y,Z,V,[],[],0);
% set(hcolorbar,'position',[.1 .05 .6 .08]);
% set(oidd,'linestyle','none')
% colorbar('hide')
% isonormals(x,y,z,V,face);
return


