function data_dialog(hObject,eventdata,handles)
% simple dialog ui for setting generic data settings
global custom
hfmain=figure;
set(hfmain,'units','pixel',...
    'position',[200, 100, 250, 450],...
    'numbertitle','off',...
    'name','data settings',...
    'menubar','none');
bcolor=get(hfmain,'color');
enable_color=[1 1 1];

%frame projection
hmp=uibuttongroup(hfmain,'units','normalized',...
    'position',[0.05 0.73 0.9 0.25],...
    'title','sites projection',...
    'backgroundcolor',bcolor,...
    'tag','sitesproject',...
    'fontweight','bold');
hmpfix=uicontrol(hmp,'style','radiobutton',...
    'units','normalized',...
    'position',[0.02 0.5 0.4 0.45],...
    'string','fixed (lat/lon)',...
    'tag','sitesprojectionfixed',...
    'backgroundcolor',bcolor);
hmplat=uicontrol(hmp,'style','edit',...
    'units','normalized',...
    'position',[0.44 0.6 0.25 0.3],...
    'backgroundcolor',enable_color,...
    'tag','lat',...
    'string',num2str(custom.centre(1)),...
    'callback',@void_callback);
hmplon=uicontrol(hmp,'style','edit',...
    'units','normalized',...
    'position',[0.74 0.6 0.25 0.3],...
    'backgroundcolor',enable_color,...
    'tag','lon',...
    'string',num2str(custom.centre(2)),...
    'callback',@void_callback);
hmpcust=uicontrol(hmp,'style','radiobutton',...
    'units','normalized',...
    'position',[0.02 0.05 0.8 0.45],...
    'string','Automatic',...
    'tag','sitesprojectioncustom',...
    'backgroundcolor',bcolor);

% frame data select
hfds=uipanel(hfmain,'units',...
    'normalized','position',...
    [0.05 0.42 0.9 0.3],'title',...
    'data select','backgroundcolor',...
    bcolor,'fontweight','bold');
hfdsc1=uicontrol(hfds,'style','checkbox',...
    'units','normalized',...
    'position',[0.02 0.67 0.4 0.31],...
    'string','Zxx&Zyy',...
    'backgroundcolor',bcolor,...
    'value',1,...
    'tag','Zxx&Zyy');
hfdsc2=uicontrol(hfds,'style','checkbox',...
    'units','normalized',...
    'position',[0.35 0.67 0.4 0.31],...
    'string','Zxy&Zyx',...
    'backgroundcolor',bcolor,...
    'value',1,...
    'tag','Zxy&Zyx');
hfdsc3=uicontrol(hfds,'style','checkbox',...
    'units','normalized',...
    'position',[0.68 0.67 0.31 0.31],...
    'string','Tx&Ty',...
    'backgroundcolor',bcolor,...
    'value',1,...
    'tag','Tx&Ty');
ht11=uicontrol(hfds,'style','text',...
    'units','normalized',...
    'position',[0.05 0.39 0.22 0.20],...
    'string','Periods:',...
    'backgroundcolor',bcolor);
hfdsfmax=uicontrol(hfds,'style','edit',...
    'units','normalized',...
    'position',[0.32 0.40 0.25 0.22],...
    'string',num2str(custom.pmin),...
    'backgroundcolor',enable_color);
ht12=uicontrol(hfds,'style','text',...
    'units','normalized',...
    'position',[0.57 0.38 0.07 0.20],...
    'string','~',...
    'backgroundcolor',bcolor);
hfdsfmin=uicontrol(hfds,'style','edit',...
    'units','normalized',...
    'position',[0.66 0.40 0.27 0.22],...
    'string',num2str(custom.pmax),...
    'backgroundcolor',enable_color);
ht13=uicontrol(hfds,'style','text',...
    'units','normalized',...
    'position',[0.94 0.38 0.05 0.20],...
    'string','s',...
    'backgroundcolor',bcolor);
ht14=uicontrol(hfds,'style','text',...
    'units','normalized',...
    'position',[0.04 0.05 0.40 0.20],...
    'string','Pers/Decade:',...
    'backgroundcolor',bcolor);
hfdsppb=uicontrol(hfds,'style','edit',...
    'units','normalized',...
    'position',[0.45 0.07 0.20 0.21],...
    'string',num2str(custom.ppd),...
    'backgroundcolor',enable_color);
hviewftable=uicontrol(hfds,'style','pushbutton',...
    'units','normalized',...
    'position',[0.72 0.07 0.25 0.22],...
    'string','Tune');

%frame data error
hme=uibuttongroup(hfmain,'units','normalized',...
    'position',[0.05 0.11 0.9 0.3],...
    'title','data error floor',...
    'fontweight','bold',...
    'backgroundcolor',bcolor);
hmefloor=uicontrol(hme,'style','radiobutton',...
    'units','normalized',...
    'position',[0.02 0.76 0.45 0.22],...
    'string','set error floor',...
    'tag','set error floor',...
    'backgroundcolor',bcolor,...
    'value',0);
ht21=uicontrol(hme,'style','text',...
    'units','normalized',...
    'position',[0.10 0.51 0.40 0.22],...
    'string','Zxx&Zyy:',...
    'backgroundcolor',bcolor);
hme1=uicontrol(hme,'style','edit',...
    'units','normalized',...
    'position',[0.55 0.54 0.25 0.22],...
    'string',num2str(custom.zxxzyye),...
    'enable','off',...
    'tag','zxxzyye',...
    'backgroundcolor',enable_color);
ht23=uicontrol(hme,'style','text',...
    'units','normalized',...
    'position',[0.82 0.51 0.08 0.22],...
    'string','%',...
    'backgroundcolor',bcolor);
ht22=uicontrol(hme,'style','text',...
    'units','normalized',...
    'position',[0.10 0.27 0.40 0.22],...
    'string','Zxy&Zyx:',...
    'backgroundcolor',bcolor);
hme2=uicontrol(hme,'style','edit',...
    'units','normalized',...
    'position',[0.55 0.30 0.25 0.22],...
    'enable','off',...
    'tag','zxyzyxe',...
    'string',num2str(custom.zxyzyxe),...
    'backgroundcolor',enable_color);
ht24=uicontrol(hme,'style','text',...
    'units','normalized',...
    'position',[0.82 0.27 0.08 0.22],...
    'string','%',...
    'backgroundcolor',bcolor);
ht25=uicontrol(hme,'style','text',...
    'units','normalized',...
    'position',[0.06 0.03 0.40 0.22],...
    'string','Tx&Ty:',...
    'backgroundcolor',bcolor);
hme3=uicontrol(hme,'style','edit',...
    'units','normalized',...
    'position',[0.55 0.06 0.25 0.22],...
    'string',num2str(custom.txtye),...
    'tag','txtye',...
    'enable','off',...
    'backgroundcolor',enable_color);
ht26=uicontrol(hme,'style','text',...
    'units','normalized',...
    'position',[0.82 0.03 0.08 0.22],...
    'string','%',...
    'backgroundcolor',bcolor);
hmecust=uicontrol(hme,'style','radiobutton',...
    'units','normalized',...
    'position',[0.55 0.76 0.45 0.22],...
    'string','from data',...
    'tag','from data',...
    'backgroundcolor',bcolor,...
    'value',1);
hquit=uicontrol(hfmain,'style','pushbutton',...
    'units','normalized',...
    'position',[0.65 0.03 0.3 0.06],...
    'string','DONE',...
    'tag','quit',...
    'enable','on');
h2.data=[hfdsc1,hfdsc2,hfdsc3,hfdsfmax,hfdsfmin,hfdsppb];
h2.project=[hmpfix,hmpcust,hmplat,hmplon];
h2.error=[hmefloor,hmecust,hme1,hme2,hme3];
h2.axis=handles.axis;
h2.parent=handles;
h2.figure=hfmain;
set(hfdsc1,'callback',{@dataselect_callback,h2});
set(hfdsc2,'callback',{@dataselect_callback,h2});
set(hfdsc3,'callback',{@dataselect_callback,h2});
set(hme,'selectionchangefcn',{@dataerror_callback,h2});

if custom.pauto==1
    set(hmpfix,'value',0);
    set(hmpcust,'value',1);
else
    set(hmpfix,'value',1);
    set(hmpcust,'value',0);
end
if custom.zxxzyy==1
    set(hfdsc1,'value',1);
else
    set(hfdsc1,'value',0);
end
if custom.zxyzyx ==1
    set(hfdsc2,'value',1);
else
    set(hfdsc2,'value',0);
end
if custom.txty ==1
    set(hfdsc3,'value',1);
else
    set(hfdsc3,'value',0);
end
if custom.usef == 1
    set(hmefloor,'value',1)
    set(hmecust,'value',0)
    if custom.zxxzyy==1      % Zxx&Zyy data is checked
        set(h2.error(3),'enable','on');
    else
        set(h2.error(3),'enable','off');
    end
    if custom.zxyzyx==1      % Zxy&Zyx data is checked
        set(h2.error(4),'enable','on');
    else
        set(h2.error(4),'enable','off');
    end        
    if custom.txty==1      % Tx&Ty data is checked
        set(h2.error(5),'enable','on');
    else
        set(h2.error(5),'enable','off');
    end        
else
    set(hmefloor,'value',0)
    set(hmecust,'value',1)
end
% set(hmp,'buttondownfcn',@project_callback);
set(hfdsfmin,'callback',{@set_flist,h2});
set(hfdsfmax,'callback',{@set_flist,h2});
set(hfdsppb,'callback',{@set_flist,h2});
set(hviewftable,'callback',{@create_freqeditor_gui,h2});
set(hme1,'callback',{@box_edit_callback,h2});
set(hme2,'callback',{@box_edit_callback,h2});
set(hme3,'callback',{@box_edit_callback,h2});
set(hmp,'selectionchangefcn',{@project_sites,h2});
set(hquit,'callback',{@quit_this,h2.figure});
return