function data=fix_var(data, nsite, nlevel)% for synthetic data only. 
% set a fixed variance for MT transfer function
% this is useful for forward data with no variances given.
% please use this function with caution 
for isite=1:nsite
    data(isite).tf_o(:,3)=...
        sqrt(data(isite).tf_o(:,4).^2+...
        data(isite).tf_o(:,5).^2)*nlevel;
    data(isite).tf_o(:,6)=...
        sqrt(data(isite).tf_o(:,4).^2+...
        data(isite).tf_o(:,5).^2)*nlevel;
    data(isite).tf_o(:,9)=...
        sqrt(data(isite).tf_o(:,7).^2+...
        data(isite).tf_o(:,8).^2)*nlevel;
    data(isite).tf_o(:,12)=...
        sqrt(data(isite).tf_o(:,7).^2+...
        data(isite).tf_o(:,8).^2)*nlevel;
    data(isite).tf_o(:,15)=nlevel;    
    data(isite).tf_o(:,18)=nlevel;   
end
return

%%================curve editor =========================%%
%            devoted to plot and edit Z (and T)curves    %
%%======================================================%%
