function model_gen_dialog(hObject,eventdata,handles)
% simple dialog ui for setting generic model parameters
global custom
hfmain=figure;
set(hfmain,'units','pixel',...
    'position',[200, 100, 250, 400],...
    'numbertitle','off',...
    'name','model generation',...
    'menubar','none');
bcolor=get(hfmain,'color');
enable_color=[1 1 1];

%frame model parameters
hmf=uipanel(hfmain,'units','normalized',...
    'position',[0.05 0.05 0.9 0.9],...
    'title','model parameters',...
    'fontweight','bold',...
    'backgroundcolor',bcolor);
hmft1=uicontrol(hmf,'style','text',...
    'units','normalized',...
    'position',[0.02 0.90 0.63 0.05],...
    'string','x block width(m):',...
    'horizontalalignment','left',...
    'backgroundcolor',bcolor);
hmft2=uicontrol(hmf,'style','text',...
    'units','normalized',...
    'position',[0.02 0.83 0.63 0.05],...
    'string','x padding blocks:',...
    'horizontalalignment','left',...
    'backgroundcolor',bcolor);
hmft3=uicontrol(hmf,'style','text',...
    'units','normalized',...
    'position',[0.02 0.76 0.63 0.05],...
    'string','x padding step:',...
    'horizontalalignment','left',...
    'backgroundcolor',bcolor);
hmft4=uicontrol(hmf,'style','text',...
    'units','normalized',...
    'position',[0.02 0.69 0.63 0.05],...
    'string','y block width(m):',...
    'horizontalalignment','left',...
    'backgroundcolor',bcolor);
hmft5=uicontrol(hmf,'style','text',...
    'units','normalized',...
    'position',[0.02 0.62 0.63 0.05],...
    'string','y padding blocks:',...
    'horizontalalignment','left',...
    'backgroundcolor',bcolor);
hmft6=uicontrol(hmf,'style','text',...
    'units','normalized',...
    'position',[0.02 0.55 0.63 0.05],...
    'string','y padding step:',...
    'horizontalalignment','left',...
    'backgroundcolor',bcolor);
hmft7=uicontrol(hmf,'style','text',...
    'units','normalized',...
    'position',[0.02 0.48 0.63 0.05],...
    'string','z first thickness(m):',...
    'horizontalalignment','left',...
    'backgroundcolor',bcolor);
hmft8=uicontrol(hmf,'style','text',...
    'units','normalized',...
    'position',[0.02 0.41 0.63 0.05],...
    'string','z incore layers:',...
    'horizontalalignment','left',...
    'backgroundcolor',bcolor);
hmft9=uicontrol(hmf,'style','text',...
    'units','normalized',...
    'position',[0.02 0.34 0.63 0.05],...
    'string','z incore step:',...
    'horizontalalignment','left',...
    'backgroundcolor',bcolor);
hmft10=uicontrol(hmf,'style','text',...
    'units','normalized',...
    'position',[0.02 0.27 0.63 0.05],...
    'string','z padding layers:',...
    'horizontalalignment','left',...
    'backgroundcolor',bcolor);
hmft11=uicontrol(hmf,'style','text',...
    'units','normalized',...
    'position',[0.02 0.20 0.63 0.05],...
    'string','z padding step:',...
    'horizontalalignment','left',...
    'backgroundcolor',bcolor);
hmft12=uicontrol(hmf,'style','text',...
    'units','normalized',...
    'position',[0.02 0.13 0.63 0.05],...
    'string','background res.:',...
    'horizontalalignment','left',...
    'backgroundcolor',bcolor);
hmfx1=uicontrol(hmf,'style','edit',...
    'units','normalized',...
    'position',[0.67 0.90 0.31 0.05],...
    'backgroundcolor',enable_color,...
    'enable','on',...
    'tag','xblockwidth',...
    'string',num2str(custom.x1),...
    'callback',@set_model_box_value);
hmfx2=uicontrol(hmf,'style','edit',...
    'units','normalized',...
    'position',[0.67 0.83 0.31 0.05],...
    'backgroundcolor',enable_color,...
    'enable','on',...
    'tag','xpaddingblocks',...
    'string',num2str(custom.x2),...
    'callback',@set_model_box_value);
hmfx3=uicontrol(hmf,'style','edit',...
    'units','normalized',...
    'position',[0.67 0.76 0.31 0.05],...
    'backgroundcolor',enable_color,...
    'enable','on',...
    'tag','xpaddingstep',...
    'string',num2str(custom.x3),...
    'callback',@set_model_box_value);
hmfy1=uicontrol(hmf,'style','edit',...
    'units','normalized',...
    'position',[0.67 0.69 0.31 0.05],...
    'backgroundcolor',enable_color,...
    'enable','on',...
    'tag','yblockwidth',...
    'string',num2str(custom.y1),...
    'callback',@set_model_box_value);
hmfy2=uicontrol(hmf,'style','edit',...
    'units','normalized',...
    'position',[0.67 0.62 0.31 0.05],...
    'backgroundcolor',enable_color,...
    'enable','on',...
    'tag','ypaddingblocks',...
    'string',num2str(custom.y2),...
    'callback',@set_model_box_value);
hmfy3=uicontrol(hmf,'style','edit',...
    'units','normalized',...
    'position',[0.67 0.55 0.31 0.05],...
    'backgroundcolor',enable_color,...
    'enable','on',...
    'tag','ypaddingstep',...
    'string',num2str(custom.y3),...
    'callback',@set_model_box_value);
hmfz1=uicontrol(hmf,'style','edit',...
    'units','normalized',...
    'position',[0.67 0.48 0.31 0.05],...
    'backgroundcolor',enable_color,...
    'enable','on',...
    'tag','zfirstthickness',...
    'string',num2str(custom.z1),...
    'callback',@set_model_box_value);
hmfz2=uicontrol(hmf,'style','edit',...
    'units','normalized',...
    'position',[0.67 0.41 0.31 0.05],...
    'backgroundcolor',enable_color,...
    'enable','on',...
    'tag','zincorelayers',...
    'string',num2str(custom.z2),...
    'callback',@set_model_box_value);
hmfz3=uicontrol(hmf,'style','edit',...
    'units','normalized',...
    'position',[0.67 0.34 0.31 0.05],...
    'backgroundcolor',enable_color,...
    'enable','on',...
    'tag','zincorestep',...
    'string',num2str(custom.z3),...
    'callback',@set_model_box_value);
hmfz4=uicontrol(hmf,'style','edit',...
    'units','normalized',...
    'position',[0.67 0.27 0.31 0.05],...
    'backgroundcolor',enable_color,...
    'enable','on',...
    'tag','zpaddinglayers',...
    'string',num2str(custom.z4),...
    'callback',@set_model_box_value);
hmfz5=uicontrol(hmf,'style','edit',...
    'units','normalized',...
    'position',[0.67 0.20 0.31 0.05],...
    'backgroundcolor',enable_color,...
    'enable','on',...
    'tag','zpaddingstep',...
    'string',num2str(custom.z5),...
    'callback',@set_model_box_value);
hmfrho=uicontrol(hmf,'style','edit',...
    'units','normalized',...
    'position',[0.67 0.13 0.31 0.05],...
    'backgroundcolor',enable_color,...
    'enable','on',...
    'tag','backgroundrho',...
    'string',num2str(custom.rho),...
    'callback',@set_model_box_value);

hgenerate=uicontrol(hmf,'style','pushbutton',...
    'units','normalized',...
    'position',[0.05 0.03 0.4 0.07],...
    'string','Generate',...
    'tag','Generate',...
    'enable','on');
hquit=uicontrol(hmf,'style','pushbutton',...
    'units','normalized',...
    'position',[0.55 0.03 0.4 0.07],...
    'string','DONE',...
    'tag','quit',...
    'enable','on');
% handles.model=[hmfx1,hmfx2,hmfx3,hmfy1,hmfy2,hmfy3,hmfz1,hmfz2,hmfz3,...
% hmfz4,hmfz5,hmfrho,hgenerate];
% set callback for controls
% set(hmpchk,'callback',{@check_site,handles});
set(hgenerate,'callback',{@generate_model,handles});
set(hquit,'callback',{@quit_this,hfmain});
return

function set_model_box_value(hObject,eventdata)
% a silly function to set the value of current text box to global struct 
% "custom"
global custom
tag = get(hObject,'tag');
txt = get(hObject,'string');
%%debug
% if strcmp(eventdata.EventName,'Action')
%   disp('box value changed')
% else
% return
% end
switch tag
    case 'xblockwidth'
        custom.x1 = str2double(txt);
    case 'xpaddingblocks'
        custom.x2 = str2double(txt);
    case 'xpaddingstep'
        custom.x3 = str2double(txt);
    case 'yblockwidth'
        custom.y1 = str2double(txt);
    case 'ypaddingblocks'
        custom.y2 = str2double(txt);
    case 'ypaddingstep'
        custom.y3 = str2double(txt);
    case 'zfirstthickness'
        custom.z1 = str2double(txt);
    case 'zincorelayers'
        custom.z2 = str2double(txt);
    case 'zincorestep'
        custom.z3 = str2double(txt);
    case 'zpaddinglayers'
        custom.z4 = str2double(txt);
    case 'zpaddingstep'
        custom.z5 = str2double(txt);
    case 'backgroundrho'
        custom.rho = str2double(txt);
    otherwise
        disp('text box tag not recognized')
        disp(['check your code for ' tag])
end
return